language: node_js
node_js:
- '6.1'
install:
  - npm install
script:
  - npm run build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: uHvLqbcBR6aQa/GrPWN3BlufnXIX/98ZQa7q/PDtt65b1Ns9ZLK07vDebi710qfyDd8n2WplxCil07ERZz6hGdNJkf3LqRN59Gk6tlUlCfG6fVP4iaF3HuRgZGLgklC0Wqea6gvuZr3mXnySc2hOcsMnqpaZ465E8M/3ipM2MkS/2Fk4AFrvSIFabaaBiCDeaWDNGRl0PjJd/UT9RMyRid/wwRBu6NhKzzdbIRplVdroJ/Og6OZ6iwKwCs/LZAChxwKG7JqVavdybIa8fnRu7qahIzIQqs0wh0LBVgOTOyZ4vQThFSwXQ3JVBWLMN1YIc0jQGbSlgl4F0ToNVOsX4G9OwE2Buh4YvG8fFQUeoOOFtQofI3c3gsh2CtSHf36aOQy1YXAIsnsPXjXb9MraQ2qrTniRPXRaPYqG4xkjlB4Zl2efMS1YajYj0O4B01HCxvuLnWHmPyyKufvViLmISBGkYvY968TTtIKj27zmyKTpUC8nyGxvTinAksqIDMMBowviSyZ/1dC1xW87pzJ9UQBywGgCtuqlU4d+Pno36WAVckgU9YYOjFLTggCNGYElOpWlyvXW498NEq+75EAGKgWzJUoirbEThUpHV3PGj05NVxT3GVO9V5BHjq22Em4L9G3Xho0M1i2n+36L0IpONcKvVRS0tAXADEGyCckB60E=
